


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."click_logs" (
    "id" bigint NOT NULL,
    "session_id" "text" NOT NULL,
    "event_type" "text" NOT NULL,
    "location" "text",
    "occurred_at" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."click_logs" OWNER TO "postgres";


ALTER TABLE "public"."click_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."click_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."selected_rows" (
    "session_id" "text" NOT NULL,
    "selected_rows" "text"[] NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "task" "text",
    "correct" boolean,
    "experience" real
);


ALTER TABLE "public"."selected_rows" OWNER TO "postgres";


ALTER TABLE ONLY "public"."click_logs"
    ADD CONSTRAINT "click_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."selected_rows"
    ADD CONSTRAINT "selected_rows_pkey" PRIMARY KEY ("session_id");



CREATE INDEX "idx_click_logs_occurred_at" ON "public"."click_logs" USING "btree" ("occurred_at" DESC);



CREATE INDEX "idx_click_logs_session_id" ON "public"."click_logs" USING "btree" ("session_id");



CREATE INDEX "idx_selected_rows_updated_at" ON "public"."selected_rows" USING "btree" ("updated_at" DESC);



CREATE POLICY "Enable All" ON "public"."selected_rows" USING (true) WITH CHECK (true);



CREATE POLICY "Enable Update" ON "public"."click_logs" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Enable insert" ON "public"."click_logs" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."click_logs" FOR SELECT USING (true);



ALTER TABLE "public"."click_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."selected_rows" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."click_logs" TO "anon";
GRANT ALL ON TABLE "public"."click_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."click_logs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."click_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."click_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."click_logs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."selected_rows" TO "anon";
GRANT ALL ON TABLE "public"."selected_rows" TO "authenticated";
GRANT ALL ON TABLE "public"."selected_rows" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































