export const pythonFiles = [
  {
    fileName: 'main.py',
    imports: [
      'from book import Book',
      'from member import Member',
      'from library import Library',
    ],
    classes: [],
    functions: [
      {
        id: 'main-function-1',
        name: 'main',
        signature: '',
        body: [
          'library = Library(max_borrowed_books=3)',
          ' ',
          '# 本の追加',
          'book1 = Book("The Hitchhiker\'s Guide to the Galaxy", "Douglas Adams", "978-0345391803")',
          'library.add_book(book1)',
          ' ',
          '# 会員の追加',
          'member1 = Member("Alice", "M001")',
          'library.add_member(member1)',
          ' ',
          '# 本の貸出',
          'library.borrow_book("M001", "978-0345391803")',
          ' ',
          '# 本の返却',
          'library.return_book("M001", "978-0345391803")',
        ],
      },
      // {
      //   id: 'main-function-2',
      //   name: 'test_code',
      //   signature: '# --- テストコード ---',
      //   body: [
      //     'if __name__ == "__main__":',
      //     '    library = Library()',
      //     ' ',
      //     '    # 本の追加',
      //     '    book1 = Book("The Hitchhiker\'s Guide to the Galaxy", "Douglas Adams", "978-0345391803")',
      //     '    book2 = Book("Pride and Prejudice", "Jane Austen", "978-0141439518")',
      //     '    book3 = Book("1984", "George Orwell", "978-0451524935")',
      //     '    book4 = Book("To Kill a Mockingbird", "Harper Lee", "978-0061120084")',
      //     '    book5 = Book("The Great Gatsby", "F. Scott Fitzgerald", "978-0743273565")',
      //     ' ',
      //     '    print(library.add_book(book1))',
      //     '    print(library.add_book(book2))',
      //     '    print(library.add_book(book3))',
      //     '    print(library.add_book(book4))',
      //     '    print(library.add_book(book5))',
      //     ' ',
      //     '    # 論理エラー1のテスト: 同じISBNの本を再度追加',
      //     '    print("\\n--- 重複本の追加テスト ---")',
      //     '    print(library.add_book(Book("Duplicate Book 1", "Author X", "978-0345391803")))',
      //     '    library.display_all_books()',
      //     ' ',
      //     '    # 会員の追加',
      //     '    print("\\n--- 会員追加テスト ---")',
      //     '    member1 = Member("Alice", "M001")',
      //     '    member2 = Member("Bob", "M002")',
      //     ' ',
      //     '    print(library.add_member(member1))',
      //     '    print(library.add_member(member2))',
      //     ' ',
      //     '    print("\\n--- 貸出テスト ---")',
      //     '    print(library.borrow_book("M001", "978-0345391803"))',
      //     '    print(library.borrow_book("M001", "978-0141439518"))',
      //     '    print(library.borrow_book("M001", "978-0451524935"))',
      //     ' ',
      //     '    # 論理エラー2のテスト: 貸出上限を超えて借りられるか',
      //     '    print(library.borrow_book("M001", "978-0061120084"))',
      //     ' ',
      //     '    print(library.borrow_book("M002", "978-0743273565"))',
      //     ' ',
      //     '    print("\\n--- 返却テスト ---")',
      //     '    print(library.return_book("M001", "978-0345391803"))',
      //     ' ',
      //     '    # 論理エラー3のテスト',
      //     '    print(library.return_book("M001", "978-0743273565"))',
      //     '    print(library.return_book("M002", "978-0743273565"))',
      //     ' ',
      //     '    print("\\n--- その他の操作 ---")',
      //     '    print(library.remove_book("978-0451524935"))',
      //     '    print(library.remove_book("INVALID_ISBN"))',
      //     '    print(library.remove_book("978-0061120084"))',
      //   ],
      // },
    ],
    footer: [],
  },
  {
    fileName: 'book.py',
    imports: [],
    classes: [
      {
        id: 'book-class-1',
        name: 'Book',
        signature: 'class Book:',
        classVars: [
          {
            id: 'book-classvar-1',
            name: '_isbn_registry',
            signature: '_isbn_registry = set()',
            body: [],
          },
        ],
        methods: [
          {
            id: 'book-method-1',
            name: '__init__',
            signature: 'def __init__(self, title, author, isbn):',
            body: [
              '    if isbn in Book._isbn_registry:',
              '        raise ValueError(f"ISBN \'{isbn}\' は既に登録されています")',
              '',
              '    self.title = title',
              '    self.author = author',
              '    self.isbn = isbn',
              '    self.is_borrowed = False',
              '',
              '    normalized = isbn.replace("-", "")',
              '    Book._isbn_registry.add(normalized)',
            ],
          },
          {
            id: 'book-method-2',
            name: '__del__',
            signature: 'def __del__(self):',
            body: [
              '    try:',
              '        Book._isbn_registry.discard(self.isbn)',
              '    except Exception:',
              '        pass',
            ],
          },
          {
            id: 'book-method-3',
            name: '__str__',
            signature: 'def __str__(self):',
            body: [
              "    return f\"'{self.title}' by {self.author} (ISBN: {self.isbn}) - {'Borrowed' if self.is_borrowed else 'Available'}\"",
            ],
          },
        ],
      },
    ],
    functions: [],
    footer: [],
  },
  {
    fileName: 'member.py',
    imports: [],
    classes: [
      {
        id: 'member-class-1',
        name: 'Member',
        signature: 'class Member:',
        methods: [
          {
            id: 'member-method-1',
            name: '__init__',
            signature: 'def __init__(self, name, member_id):',
            body: [
              '    self.name = name',
              '    self.member_id = member_id',
              '    self.borrowed_books = []',
            ],
          },
          {
            id: 'member-method-2',
            name: '__str__',
            signature: 'def __str__(self):',
            body: ['    return f"Member: {self.name} (ID: {self.member_id})"'],
          },
        ],
      },
    ],
    functions: [],
    footer: [],
  },
  {
    fileName: 'library.py',
    imports: [],
    classes: [
      {
        id: 'library-class-1',
        name: 'Library',
        signature: 'class Library:',
        methods: [
          {
            id: 'library-method-1',
            name: '__init__',
            signature: 'def __init__(self, max_borrowed_books = 3):',
            body: [
              '    self.books = {}',
              '    self.members = {}',
              '    self.MAX_BORROWED_BOOKS = max_borrowed_books',
            ],
          },
          {
            id: 'library-method-2',
            name: 'add_book',
            signature: 'def add_book(self, book):',
            body: [
              '    self.books[book.isbn] = book',
              '    return f"Book \'{book.title}\' added to the library."',
            ],
          },
          {
            id: 'library-method-3',
            name: 'remove_book',
            signature: 'def remove_book(self, isbn):',
            body: [
              '    if isbn not in self.books:',
              '        return "Error: Book not found."',
              '    if self.books[isbn].is_borrowed:',
              '        return "Error: Cannot remove a borrowed book."',
              '    del self.books[isbn]',
              '    return "Book removed successfully."',
            ],
          },
          {
            id: 'library-method-4',
            name: 'add_member',
            signature: 'def add_member(self, member):',
            body: [
              '    if member.member_id in self.members:',
              '        return "Error: Member with this ID already exists."',
              '    self.members[member.member_id] = member',
              '    return f"Member \'{member.name}\' added."',
            ],
          },
          {
            id: 'library-method-5',
            name: 'remove_member',
            signature: 'def remove_member(self, member_id):',
            body: [
              '    if member_id not in self.members:',
              '        return "Error: Member not found."',
              '    if self.members[member_id].borrowed_books:',
              '        return "Error: Cannot remove member with borrowed books."',
              '    del self.members[member_id]',
              '    return "Member removed successfully."',
            ],
          },
          {
            id: 'library-method-6',
            name: 'borrow_book',
            signature: 'def borrow_book(self, member_id, isbn):',
            body: [
              '    if member_id not in self.members:',
              '        return "Error: Member not found."',
              '    if isbn not in self.books:',
              '        return "Error: Book not found."',
              ' ',
              '    book = self.books[isbn]',
              '    member = self.members[member_id]',
              ' ',
              '    if book.is_borrowed:',
              '        return "Error: Book is already borrowed."',
              ' ',
              '    if len(member.borrowed_books) > self.MAX_BORROWED_BOOKS:',
              '        return "Error: Member has reached the maximum borrowing limit."',
              ' ',
              '    book.is_borrowed = True',
              '    member.borrowed_books.append(book)',
              '    return f"Book \'{book.title}\' borrowed by {member.name}."',
            ],
          },
          {
            id: 'library-method-7',
            name: 'return_book',
            signature: 'def return_book(self, member_id, isbn):',
            body: [
              '    if member_id not in self.members:',
              '        return "Error: Member not found."',
              '    if isbn not in self.books:',
              '        return "Error: Book not found."',
              ' ',
              '    book = self.books[isbn]',
              '    member = self.members[member_id]',
              ' ',
              '    if not book.is_borrowed:',
              '        return "Error: Book is not currently borrowed."',
              ' ',
              '    if book in member.borrowed_books:',
              '        member.borrowed_books.remove(book)',
              '    book.is_borrowed = False',
              '    return f"Book \'{book.title}\' returned by {member.name}."',
            ],
          },
          {
            id: 'library-method-8',
            name: 'get_available_books',
            signature: 'def get_available_books(self):',
            body: [
              '    return [book for book in self.books.values() if not book.is_borrowed]',
            ],
          },
          {
            id: 'library-method-9',
            name: 'get_borrowed_books_by_member',
            signature: 'def get_borrowed_books_by_member(self, member_id):',
            body: [
              '    if member_id not in self.members:',
              '        return "Error: Member not found."',
              '    return self.members[member_id].borrowed_books',
            ],
          },
          {
            id: 'library-method-10',
            name: 'display_all_books',
            signature: 'def display_all_books(self):',
            body: [
              '    if not self.books:',
              '        print("No books in the library.")',
              '        return',
              '    print("\\n--- All Books ---")',
              '    for book in self.books.values():',
              '        print(book)',
            ],
          },
          {
            id: 'library-method-11',
            name: 'display_all_members',
            signature: 'def display_all_members(self):',
            body: [
              '    if not self.members:',
              '        print("No members in the library.")',
              '        return',
              '    print("\\n--- All Members ---")',
              '    for member in self.members.values():',
              '        print(member)',
              '        if member.borrowed_books:',
              '            print("  Borrowed Books:")',
              '            for book in member.borrowed_books:',
              '                print(f"  - \'{book.title}\'")',
              '        else:',
              '            print("  No books borrowed.")',
            ],
          },
        ],
      },
    ],
    functions: [],
    footer: [],
  },
];

export const trainingPythonFiles = [
  {
    fileName: 'main.py',
    imports: ['from fizzbuzz import fizzbuzz'],
    classes: [],
    functions: [
      {
        id: 'training-main-function-1',
        name: 'main',
        signature: '',
        body: ['for i in range(1, 16):', '    print(fizzbuzz(i))'],
      },
    ],
    footer: [],
  },
  {
    fileName: 'fizzbuzz.py',
    imports: [],
    classes: [],
    functions: [
      {
        id: 'fizzbuzz-function-1',
        name: 'fizzbuzz',
        signature: 'def fizzbuzz(n):',
        body: [
          '    if n % 15 == 0:',
          '        return "FizzBuzz"',
          '    elif n % 3 == 0:',
          '        return "Fizz"',
          '    elif n % 5 = 0:    # バグ："== " が "=" になっている',
          '        return "Buzz"',
          '    else:',
          '        return str(n)',
        ],
      },
    ],
    footer: [],
  },
];

export default pythonFiles;
