export const pythonFiles = [
  {
    fileName: 'main.py',
    imports: [
      'from book import Book',
      'from member import Member',
      'from library import Library',
    ],
    classes: [],
    functions: [
      {
        id: 'main-function-1',
        name: 'main',
        signature: '',
        body: [
          'library = Library(max_borrowed_books=3)',
          '',
          '# 本の追加',
          'book1 = Book("The Hitchhiker\'s Guide to the Galaxy", "Douglas Adams", "978-0345391803")',
          'book2 = Book("Pride and Prejudice", "Jane Austen", "978-0141439518")',
          'book3 = Book("1984", "George Orwell", "978-0451524935")',
          'book4 = Book("To Kill a Mockingbird", "Harper Lee", "978-0061120084")',
          'book5 = Book("The Great Gatsby", "F. Scott Fitzgerald", "978-0743273565")',
          'library.add_book([book1, book2, book3, book4, book5])',
          '',
          '# 会員の追加',
          'member1 = Member("Alice")',
          'library.add_member(member1)',
          'member2 = Member("Bob")',
          'library.add_member(member2)',
          '',
          '# 本の貸出',
          'library.borrow_book(member1.member_id, [book1.isbn, book2.isbn, book3.isbn])',
          'library.borrow_book(member2.member_id, [book4.isbn])',
          '',
          '# 本の返却',
          'library.return_book(member1.member_id, [book1.isbn])',
          '',
          '# 本の削除',
          'library.remove_book([book5.isbn])',
        ],
      },
    ],
    footer: [],
  },
  {
    fileName: 'book.py',
    imports: [],
    classes: [
      {
        id: 'book-class-1',
        name: 'Book',
        signature: 'class Book:',
        classVars: [
          {
            id: 'book-classvar-1',
            name: '_isbn_registry',
            signature: '_isbn_registry = set()',
            body: [],
          },
        ],
        methods: [
          {
            id: 'book-method-1',
            name: '__init__',
            signature: 'def __init__(self, title, author, isbn):',
            body: [
              '    if isbn in Book._isbn_registry:',
              '        raise ValueError(f"ISBN \'{isbn}\' は既に登録されています")',
              '',
              '    self.title = title',
              '    self.author = author',
              '    self.isbn = isbn',
              '    self.is_borrowed = False',
              '',
              '    normalized = isbn.replace("-", "")',
              '    Book._isbn_registry.add(normalized)',
            ],
          },
          {
            id: 'book-method-2',
            name: '__del__',
            signature: 'def __del__(self):',
            body: [
              '    try:',
              '        Book._isbn_registry.discard(self.isbn)',
              '    except Exception:',
              '        pass',
            ],
          },
          {
            id: 'book-method-3',
            name: '__str__',
            signature: 'def __str__(self):',
            body: [
              "    return f\"'{self.title}' by {self.author} (ISBN: {self.isbn}) - {'Borrowed' if self.is_borrowed else 'Available'}\"",
            ],
          },
        ],
      },
    ],
    functions: [],
    footer: [],
  },
  {
    fileName: 'member.py',
    imports: ['import random', 'import string', ''],
    classes: [
      {
        id: 'member-class-1',
        name: 'Member',
        signature: 'class Member:',
        methods: [
          {
            id: 'member-method-1',
            name: '__init__',
            signature: 'def __init__(self, name):',
            body: [
              '    self.name = name',
              '    self.member_id = Member._random_id()',
              '    self.borrowed_books = []',
            ],
          },
          {
            id: 'member-method-2',
            name: '_random_id',
            signature: '@staticmethod\ndef _random_id(length = 10):',
            body: [
              '    # ランダムなIDの生成',
              '    chars = string.ascii_letters + string.digits',
              '    return "".join(random.choice(chars) for _ in range(length))',
            ],
          },
          {
            id: 'member-method-3',
            name: '__str__',
            signature: 'def __str__(self):',
            body: ['    return f"Member: {self.name} (ID: {self.member_id})"'],
          },
        ],
      },
    ],
    functions: [],
    footer: [],
  },
  {
    fileName: 'library.py',
    imports: [],
    classes: [
      {
        id: 'library-class-1',
        name: 'Library',
        signature: 'class Library:',
        methods: [
          {
            id: 'library-method-1',
            name: '__init__',
            signature: 'def __init__(self, max_borrowed_books = 3):',
            body: [
              '    self.books = {}',
              '    self.members = {}',
              '    self.MAX_BORROWED_BOOKS = max_borrowed_books',
            ],
          },
          {
            id: 'library-method-2',
            name: 'add_book',
            signature: 'def add_book(self, books):',
            body: [
              '    for book in books:',
              '        self.books[book.isbn] = book',
              '    return "All requested books added successfully."',
            ],
          },
          {
            id: 'library-method-3',
            name: 'remove_book',
            signature: 'def remove_book(self, isbns):',
            body: [
              '    failed_isbns = []',
              '',
              '    for isbn in isbns:',
              '        if isbn not in self.books:',
              '            failed_isbns.append(isbn)',
              '            continue',
              '        if self.books[isbn].is_borrowed:',
              '            failed_isbns.append(isbn)',
              '            continue',
              '        del self.books[isbn]',
              '',
              '    if failed_isbns:',
              '        return f"Failed to remove ISBNs: {failed_isbns}"',
              '',
              '    return "All requested books removed successfully."',
            ],
          },
          {
            id: 'library-method-4',
            name: 'add_member',
            signature: 'def add_member(self, member):',
            body: [
              '    if member.member_id in self.members:',
              '        return "Error: Member with this ID already exists."',
              '    self.members[member.member_id] = member',
              '    return f"Member \'{member.name}\' added."',
            ],
          },
          {
            id: 'library-method-5',
            name: 'remove_member',
            signature: 'def remove_member(self, member_id):',
            body: [
              '    if member_id not in self.members:',
              '        return "Error: Member not found."',
              '',
              '    if self.members[member_id].borrowed_books:',
              '        return "Error: Cannot remove member with borrowed books."',
              '',
              '    del self.members[member_id]',
              '    return "Member removed successfully."',
            ],
          },
          {
            id: 'library-method-6',
            name: 'borrow_book',
            signature: 'def borrow_book(self, member_id, isbns):',
            body: [
              '    if member_id not in self.members:',
              '        return "Error: Member not found."',
              '',
              '    member = self.members[member_id]',
              '',
              '    for i in isbns:',
              '        if i not in self.books:',
              '            return f"Error: Book with ISBN {i} not found."',
              '        if self.books[i].is_borrowed:',
              '            return f"Error: Book with ISBN {i} is already borrowed."',
              '',
              '    for i in isbns:',
              '        book = self.books[i]',
              '',
              '        if len(member.borrowed_books) > self.MAX_BORROWED_BOOKS:',
              '            return "Error: Member has reached the maximum borrowing limit."',
              '',
              '        book.is_borrowed = True',
              '        member.borrowed_books.append(book)',
              '',
              '    return "All requested books borrowed successfully."',
            ],
          },
          {
            id: 'library-method-7',
            name: 'return_book',
            signature: 'def return_book(self, member_id, isbns):',
            body: [
              '    if member_id not in self.members:',
              '        return "Error: Member not found."',
              '',
              '    member = self.members[member_id]',
              '',
              '    for i in isbns:',
              '        if i not in self.books:',
              '            return f"Error: Book with ISBN {i} not found."',
              '',
              '        book = self.books[i]',
              '',
              '        if book in member.borrowed_books:',
              '            member.borrowed_books.remove(book)',
              '        book.is_borrowed = False',
              '',
              '    return "All requested books returned successfully."',
            ],
          },
        ],
      },
    ],
    functions: [],
    footer: [],
  },
];

export const trainingPythonFiles = [
  {
    fileName: 'main.py',
    imports: ['from fizzbuzz import fizzbuzz'],
    classes: [],
    functions: [
      {
        id: 'training-main-function-1',
        name: 'main',
        signature: '',
        body: ['for i in range(1, 16):', '    print(fizzbuzz(i))'],
      },
    ],
    footer: [],
  },
  {
    fileName: 'fizzbuzz.py',
    imports: [],
    classes: [],
    functions: [
      {
        id: 'fizzbuzz-function-1',
        name: 'fizzbuzz',
        signature: 'def fizzbuzz(n):',
        body: [
          '    if n % 15 == 0:',
          '        return "FizzBuzz"',
          '    elif n % 3 == 0:',
          '        return "Fizz"',
          '    elif n % 5 = 0:    # バグ："== " が "=" になっている',
          '        return "Buzz"',
          '    else:',
          '        return str(n)',
        ],
      },
    ],
    footer: [],
  },
];

export default pythonFiles;
