-- Create table for storing client-side click logs
-- Run this in the Supabase SQL editor (or via psql against your DB)

CREATE TABLE IF NOT EXISTS public.click_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  location TEXT,
  occurred_at TIMESTAMPTZ NOT NULL,
  meta JSONB
);

-- Optional: indexes for common queries
CREATE INDEX IF NOT EXISTS idx_click_logs_session_id ON public.click_logs(session_id);
CREATE INDEX IF NOT EXISTS idx_click_logs_occurred_at ON public.click_logs(occurred_at DESC);

-- Notes:
-- - The client currently stores timestamps as epoch milliseconds (Date.now()). When inserting
--   from a server API, convert to timestamptz with: to_timestamp(epoch_ms / 1000.0)
--   Example insert (server-side):
--     INSERT INTO public.click_logs (session_id, event_type, location, occurred_at, meta)
--     VALUES ('session-xxxx', 'tab', 'main.py', to_timestamp(1690000000000/1000.0), '{"extra":true}'::jsonb);
